#!/bin/bash

brew install homebrew/cask/google-chrome
brew install homebrew/cask/iterm2
brew install homebrew/cask/sublime-text
brew install visual-studio-code

brew install 1password
brew install zoom
brew install slack
brew install tunnelblick

brew install bartender
brew install transmit
brew install keka
brew install intellij-idea-ce
brew install spotify
brew install yarn
# backblaze

brew install lulu
brew install karabiner-elements
brew install alfred
brew install whatsapp
brew install libreoffice

mas install 1503136033   # service station
