#!/bin/bash

# misc. macos configuration

## show all files in finder
defaults write com.apple.finder AppleShowAllFiles -string YES

## show all extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

## show path in finder
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
defaults write com.apple.finder PathBarRootAtHome -bool TRUE

defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false@

killall Finder

## enable safari debug menu
defaults write com.apple.Safari IncludeInternalDebugMenu 1


